### ISSUE TITLE
omp parallel for raises segmentation fault(core dumped) when the number of iterations in the for loop exceed a certain amount.

### ISSUE THREAD

**Issue by arghyadeep-paul** [OpenMP/sources#1]
I have been writing a code and have tried to parallelize it using #pragma omp parallel for. Everything works fine till about 100000 iterations but whe i increase the number of iterations to about 200000, it compiles  without errors but while running shows the error "segmentation fault(core dumped) " immidiately. 
I have been told that it might be local/global variable issue of the iteration variables but i think it is unlikely because it runs just fine if the number of iteration is lesser.
Also i have been told that it might be stack issue which i have no idea about

**Comment by mjklemm** [comment]
I will have to close this issue, as your issue report seems to not be related with this repository.  This place is to host source code (e..g., the OpenMP stub library) that augments the OpenMP API specification.

I would like to refer you to StackOverflow and the OpenMP tag there: https://stackoverflow.com/questions/tagged/openmp.  Please see if an answer to your question is already listed there and if not, please post a new question that includes a reproducer for the community to help debug the problem.  Thanks!
